### ISSUE TITLE
Allow more flexibility in model locations and locations

### ISSUE THREAD

**Issue by benson-basis** [emorynlp/nlp4j#4]
It would helpful to be able to have models anywhere reachable by Path. That includes, for example, S3 and HDFS. It would be helpful to be able to trade space for time by allow for things that are not necessarily xz-compressed.

**Comment by jdchoi77** [comment]
Two things I noticed:
- Several methods such as `createXZBufferedInputStream` are removed from this change, which is not good since those functions are used everywhere including our internal projects depending on NLP4J APIs.  I would suggest to create the other methods without removing them.
- Taking `InputStream` as a parameter instead of actual `String` path had been requested by several users who wanted to load models in different formats. How about overriding these methods so they can take either `String` path or `InputStream`?

Thanks!

**Comment by benson-basis** [comment]
OK, I see. I'll fix it up.

**Comment by benson-basis** [comment]
I thought about this some more. I'm going to replace this PR with one that
makes many fewer changes and preserves compatibility. Making the changes I
made and also being compatible is looking really messy to me.

**Comment by benson-basis** [comment]
@jdchoi77 With the current API, it practical to set up an decoder with no XML file at all? If so, I'm not sure that any of this work is particularly needed. I convinced myself that the XML file was unavoidable, but now I'm not so sure after your remarks. Or, to put it another way, I bet I could come up with a far smaller set of changes to facilitate that approach than the set in the PR.
